### ISSUE TITLE
Import Files and Discuss Redesigned Template

### ISSUE THREAD

**Issue by StelterPaulSearcy** [stelter/StelterMasterLayoutRefresh#1]
Import files from old repository and discuss what changes are wanted and what will be eventually added later.

**Comment by chrisbutzke** [comment]
Updated default template files for strategy meeting: files located in departments > web > chris

Updated snippets doc: https://docs.google.com/document/d/1FQ1hMOSMMlmoVQMYBVnUeKEACYbS8PQ6W3TNV3rJtfA/edit
